[tool.poetry]
name = "data-pipeline"
version = "0.1.0"
description = "Crypto Data pipeline"
authors = ["CannedKilroy <GenericArt@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
